# resolve-type-names: false

class ::Image < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Image, ::Image::ActiveRecord_Relation, ::String]

  module ::Image::GeneratedAttributeMethods
    def id: () -> ::String

    def id=: (::String) -> ::String

    def id?: () -> bool

    def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_change: () -> [ ::String?, ::String? ]

    def id_will_change!: () -> void

    def id_was: () -> ::String?

    def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_previous_change: () -> ::Array[::String?]?

    def id_previously_was: () -> ::String?

    def id_before_last_save: () -> ::String?

    def id_change_to_be_saved: () -> ::Array[::String?]?

    def id_in_database: () -> ::String?

    def saved_change_to_id: () -> ::Array[::String?]?

    def saved_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::String

    def id_for_database: () -> ::String

    def cdn_url: () -> ::String

    def cdn_url=: (::String) -> ::String

    def cdn_url?: () -> bool

    def cdn_url_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def cdn_url_change: () -> [ ::String?, ::String? ]

    def cdn_url_will_change!: () -> void

    def cdn_url_was: () -> ::String?

    def cdn_url_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def cdn_url_previous_change: () -> ::Array[::String?]?

    def cdn_url_previously_was: () -> ::String?

    def cdn_url_before_last_save: () -> ::String?

    def cdn_url_change_to_be_saved: () -> ::Array[::String?]?

    def cdn_url_in_database: () -> ::String?

    def saved_change_to_cdn_url: () -> ::Array[::String?]?

    def saved_change_to_cdn_url?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_cdn_url?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_cdn_url!: () -> void

    def clear_cdn_url_change: () -> void

    def cdn_url_before_type_cast: () -> ::String

    def cdn_url_for_database: () -> ::String

    def content_hash: () -> ::String

    def content_hash=: (::String) -> ::String

    def content_hash?: () -> bool

    def content_hash_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def content_hash_change: () -> [ ::String?, ::String? ]

    def content_hash_will_change!: () -> void

    def content_hash_was: () -> ::String?

    def content_hash_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def content_hash_previous_change: () -> ::Array[::String?]?

    def content_hash_previously_was: () -> ::String?

    def content_hash_before_last_save: () -> ::String?

    def content_hash_change_to_be_saved: () -> ::Array[::String?]?

    def content_hash_in_database: () -> ::String?

    def saved_change_to_content_hash: () -> ::Array[::String?]?

    def saved_change_to_content_hash?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_content_hash?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_content_hash!: () -> void

    def clear_content_hash_change: () -> void

    def content_hash_before_type_cast: () -> ::String

    def content_hash_for_database: () -> ::String

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def mime_type: () -> ::String

    def mime_type=: (::String) -> ::String

    def mime_type?: () -> bool

    def mime_type_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def mime_type_change: () -> [ ::String?, ::String? ]

    def mime_type_will_change!: () -> void

    def mime_type_was: () -> ::String?

    def mime_type_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def mime_type_previous_change: () -> ::Array[::String?]?

    def mime_type_previously_was: () -> ::String?

    def mime_type_before_last_save: () -> ::String?

    def mime_type_change_to_be_saved: () -> ::Array[::String?]?

    def mime_type_in_database: () -> ::String?

    def saved_change_to_mime_type: () -> ::Array[::String?]?

    def saved_change_to_mime_type?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_mime_type?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_mime_type!: () -> void

    def clear_mime_type_change: () -> void

    def mime_type_before_type_cast: () -> ::String

    def mime_type_for_database: () -> ::String

    def source_url: () -> ::String

    def source_url=: (::String) -> ::String

    def source_url?: () -> bool

    def source_url_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def source_url_change: () -> [ ::String?, ::String? ]

    def source_url_will_change!: () -> void

    def source_url_was: () -> ::String?

    def source_url_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def source_url_previous_change: () -> ::Array[::String?]?

    def source_url_previously_was: () -> ::String?

    def source_url_before_last_save: () -> ::String?

    def source_url_change_to_be_saved: () -> ::Array[::String?]?

    def source_url_in_database: () -> ::String?

    def saved_change_to_source_url: () -> ::Array[::String?]?

    def saved_change_to_source_url?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_source_url?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_source_url!: () -> void

    def clear_source_url_change: () -> void

    def source_url_before_type_cast: () -> ::String

    def source_url_for_database: () -> ::String

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time
  end
  include ::Image::GeneratedAttributeMethods
  module ::Image::GeneratedAliasAttributeMethods
    include ::Image::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::Image::GeneratedAliasAttributeMethods

  def image_file_attachment: () -> ::ActiveStorage::Attachment?
  def image_file_attachment=: (::ActiveStorage::Attachment?) -> ::ActiveStorage::Attachment?
  def build_image_file_attachment: (?untyped) -> ::ActiveStorage::Attachment
  def create_image_file_attachment: (?untyped) -> ::ActiveStorage::Attachment
  def create_image_file_attachment!: (?untyped) -> ::ActiveStorage::Attachment
  def reload_image_file_attachment: () -> ::ActiveStorage::Attachment?
  def image_file_blob: () -> ::ActiveStorage::Blob?
  def image_file_blob=: (::ActiveStorage::Blob?) -> ::ActiveStorage::Blob?
  def build_image_file_blob: (?untyped) -> ::ActiveStorage::Blob
  def create_image_file_blob: (?untyped) -> ::ActiveStorage::Blob
  def create_image_file_blob!: (?untyped) -> ::ActiveStorage::Blob
  def reload_image_file_blob: () -> ::ActiveStorage::Blob?

  module ::Image::GeneratedAssociationMethods
    def image_file: () -> ::ActiveStorage::Attached::One

    def image_file=: (::ActionDispatch::Http::UploadedFile) -> ::ActionDispatch::Http::UploadedFile
                   | (::Rack::Test::UploadedFile) -> ::Rack::Test::UploadedFile
                   | (::ActiveStorage::Blob) -> ::ActiveStorage::Blob
                   | (::String) -> ::String
                   | ({ io: ::IO, filename: ::String, content_type: ::String? }) -> { io: ::IO, filename: ::String, content_type: ::String? }
                   | (nil) -> nil
  end
  include ::Image::GeneratedAssociationMethods

  def self.with_attached_image_file: () -> ::Image::ActiveRecord_Relation

  module ::Image::GeneratedRelationMethods
    def with_attached_image_file: () -> ::Image::ActiveRecord_Relation
  end

  class ::Image::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Image]
    include ::Image::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Image, ::String]
  end

  class ::Image::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Image]
    include ::Image::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Image, ::String]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Image
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Image]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Image
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Image]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Image
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Image]
    def reload: () -> ::Array[::Image]

    def replace: (::Array[::Image]) -> void
    def delete: (*::Image | ::String) -> ::Array[::Image]
    def destroy: (*::Image | ::String) -> ::Array[::Image]
    def <<: (*::Image | ::Array[::Image]) -> self
    def prepend: (*::Image | ::Array[::Image]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
