# resolve-type-names: false

class ::Locale < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Locale, ::Locale::ActiveRecord_Relation, ::String]

  module ::Locale::GeneratedAttributeMethods
    def id: () -> ::String

    def id=: (::String) -> ::String

    def id?: () -> bool

    def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_change: () -> [ ::String?, ::String? ]

    def id_will_change!: () -> void

    def id_was: () -> ::String?

    def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_previous_change: () -> ::Array[::String?]?

    def id_previously_was: () -> ::String?

    def id_before_last_save: () -> ::String?

    def id_change_to_be_saved: () -> ::Array[::String?]?

    def id_in_database: () -> ::String?

    def saved_change_to_id: () -> ::Array[::String?]?

    def saved_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::String

    def id_for_database: () -> ::String

    def audience_id: () -> ::String

    def audience_id=: (::String) -> ::String

    def audience_id?: () -> bool

    def audience_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def audience_id_change: () -> [ ::String?, ::String? ]

    def audience_id_will_change!: () -> void

    def audience_id_was: () -> ::String?

    def audience_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def audience_id_previous_change: () -> ::Array[::String?]?

    def audience_id_previously_was: () -> ::String?

    def audience_id_before_last_save: () -> ::String?

    def audience_id_change_to_be_saved: () -> ::Array[::String?]?

    def audience_id_in_database: () -> ::String?

    def saved_change_to_audience_id: () -> ::Array[::String?]?

    def saved_change_to_audience_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_audience_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_audience_id!: () -> void

    def clear_audience_id_change: () -> void

    def audience_id_before_type_cast: () -> ::String

    def audience_id_for_database: () -> ::String

    def beacon_major: () -> ::Integer?

    def beacon_major=: (::Integer?) -> ::Integer?

    def beacon_major?: () -> bool

    def beacon_major_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def beacon_major_change: () -> [ ::Integer?, ::Integer? ]

    def beacon_major_will_change!: () -> void

    def beacon_major_was: () -> ::Integer?

    def beacon_major_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def beacon_major_previous_change: () -> ::Array[::Integer?]?

    def beacon_major_previously_was: () -> ::Integer?

    def beacon_major_before_last_save: () -> ::Integer?

    def beacon_major_change_to_be_saved: () -> ::Array[::Integer?]?

    def beacon_major_in_database: () -> ::Integer?

    def saved_change_to_beacon_major: () -> ::Array[::Integer?]?

    def saved_change_to_beacon_major?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_beacon_major?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_beacon_major!: () -> void

    def clear_beacon_major_change: () -> void

    def beacon_major_before_type_cast: () -> ::Integer?

    def beacon_major_for_database: () -> ::Integer?

    def city_names: () -> ::String?

    def city_names=: (::String?) -> ::String?

    def city_names?: () -> bool

    def city_names_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def city_names_change: () -> [ ::String?, ::String? ]

    def city_names_will_change!: () -> void

    def city_names_was: () -> ::String?

    def city_names_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def city_names_previous_change: () -> ::Array[::String?]?

    def city_names_previously_was: () -> ::String?

    def city_names_before_last_save: () -> ::String?

    def city_names_change_to_be_saved: () -> ::Array[::String?]?

    def city_names_in_database: () -> ::String?

    def saved_change_to_city_names: () -> ::Array[::String?]?

    def saved_change_to_city_names?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_city_names?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_city_names!: () -> void

    def clear_city_names_change: () -> void

    def city_names_before_type_cast: () -> ::String?

    def city_names_for_database: () -> ::String?

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def envelope: () -> untyped

    def envelope=: (untyped) -> untyped

    def envelope?: () -> bool

    def envelope_changed?: (?from: untyped, ?to: untyped) -> bool

    def envelope_change: () -> [ untyped, untyped ]

    def envelope_will_change!: () -> void

    def envelope_was: () -> untyped

    def envelope_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    def envelope_previous_change: () -> ::Array[untyped]?

    def envelope_previously_was: () -> untyped

    def envelope_before_last_save: () -> untyped

    def envelope_change_to_be_saved: () -> ::Array[untyped]?

    def envelope_in_database: () -> untyped

    def saved_change_to_envelope: () -> ::Array[untyped]?

    def saved_change_to_envelope?: (?from: untyped, ?to: untyped) -> bool

    def will_save_change_to_envelope?: (?from: untyped, ?to: untyped) -> bool

    def restore_envelope!: () -> void

    def clear_envelope_change: () -> void

    def envelope_before_type_cast: () -> untyped?

    def envelope_for_database: () -> untyped?

    def label: () -> ::String?

    def label=: (::String?) -> ::String?

    def label?: () -> bool

    def label_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def label_change: () -> [ ::String?, ::String? ]

    def label_will_change!: () -> void

    def label_was: () -> ::String?

    def label_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def label_previous_change: () -> ::Array[::String?]?

    def label_previously_was: () -> ::String?

    def label_before_last_save: () -> ::String?

    def label_change_to_be_saved: () -> ::Array[::String?]?

    def label_in_database: () -> ::String?

    def saved_change_to_label: () -> ::Array[::String?]?

    def saved_change_to_label?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_label?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_label!: () -> void

    def clear_label_change: () -> void

    def label_before_type_cast: () -> ::String?

    def label_for_database: () -> ::String?

    def location_id: () -> ::String?

    def location_id=: (::String?) -> ::String?

    def location_id?: () -> bool

    def location_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def location_id_change: () -> [ ::String?, ::String? ]

    def location_id_will_change!: () -> void

    def location_id_was: () -> ::String?

    def location_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def location_id_previous_change: () -> ::Array[::String?]?

    def location_id_previously_was: () -> ::String?

    def location_id_before_last_save: () -> ::String?

    def location_id_change_to_be_saved: () -> ::Array[::String?]?

    def location_id_in_database: () -> ::String?

    def saved_change_to_location_id: () -> ::Array[::String?]?

    def saved_change_to_location_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_location_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_location_id!: () -> void

    def clear_location_id_change: () -> void

    def location_id_before_type_cast: () -> ::String?

    def location_id_for_database: () -> ::String?

    def name: () -> ::String?

    def name=: (::String?) -> ::String?

    def name?: () -> bool

    def name_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def name_change: () -> [ ::String?, ::String? ]

    def name_will_change!: () -> void

    def name_was: () -> ::String?

    def name_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def name_previous_change: () -> ::Array[::String?]?

    def name_previously_was: () -> ::String?

    def name_before_last_save: () -> ::String?

    def name_change_to_be_saved: () -> ::Array[::String?]?

    def name_in_database: () -> ::String?

    def saved_change_to_name: () -> ::Array[::String?]?

    def saved_change_to_name?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_name?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_name!: () -> void

    def clear_name_change: () -> void

    def name_before_type_cast: () -> ::String?

    def name_for_database: () -> ::String?

    def timezone_zulu_delta: () -> ::Integer?

    def timezone_zulu_delta=: (::Integer?) -> ::Integer?

    def timezone_zulu_delta?: () -> bool

    def timezone_zulu_delta_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def timezone_zulu_delta_change: () -> [ ::Integer?, ::Integer? ]

    def timezone_zulu_delta_will_change!: () -> void

    def timezone_zulu_delta_was: () -> ::Integer?

    def timezone_zulu_delta_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def timezone_zulu_delta_previous_change: () -> ::Array[::Integer?]?

    def timezone_zulu_delta_previously_was: () -> ::Integer?

    def timezone_zulu_delta_before_last_save: () -> ::Integer?

    def timezone_zulu_delta_change_to_be_saved: () -> ::Array[::Integer?]?

    def timezone_zulu_delta_in_database: () -> ::Integer?

    def saved_change_to_timezone_zulu_delta: () -> ::Array[::Integer?]?

    def saved_change_to_timezone_zulu_delta?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_timezone_zulu_delta?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_timezone_zulu_delta!: () -> void

    def clear_timezone_zulu_delta_change: () -> void

    def timezone_zulu_delta_before_type_cast: () -> ::Integer?

    def timezone_zulu_delta_for_database: () -> ::Integer?

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time
  end
  include ::Locale::GeneratedAttributeMethods
  module ::Locale::GeneratedAliasAttributeMethods
    include ::Locale::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::Locale::GeneratedAliasAttributeMethods
  def venues: () -> ::Venue::ActiveRecord_Associations_CollectionProxy
  def venues=: (::Venue::ActiveRecord_Associations_CollectionProxy | ::Array[::Venue]) -> (::Venue::ActiveRecord_Associations_CollectionProxy | ::Array[::Venue])
  def venue_ids: () -> ::Array[::String]
  def venue_ids=: (::Array[::String]) -> ::Array[::String]
  def people: () -> ::Person::ActiveRecord_Associations_CollectionProxy
  def people=: (::Person::ActiveRecord_Associations_CollectionProxy | ::Array[::Person]) -> (::Person::ActiveRecord_Associations_CollectionProxy | ::Array[::Person])
  def person_ids: () -> ::Array[::String]
  def person_ids=: (::Array[::String]) -> ::Array[::String]
  def events: () -> ::Event::ActiveRecord_Associations_CollectionProxy
  def events=: (::Event::ActiveRecord_Associations_CollectionProxy | ::Array[::Event]) -> (::Event::ActiveRecord_Associations_CollectionProxy | ::Array[::Event])
  def event_ids: () -> ::Array[::String]
  def event_ids=: (::Array[::String]) -> ::Array[::String]
  def locations: () -> ::Location::ActiveRecord_Associations_CollectionProxy
  def locations=: (::Location::ActiveRecord_Associations_CollectionProxy | ::Array[::Location]) -> (::Location::ActiveRecord_Associations_CollectionProxy | ::Array[::Location])
  def location_ids: () -> ::Array[::String]
  def location_ids=: (::Array[::String]) -> ::Array[::String]

  def image: () -> ::Image
  def image=: (::Image?) -> ::Image?
  def reload_image: () -> ::Image?
  def build_image: (?untyped) -> ::Image
  def create_image: (?untyped) -> ::Image
  def create_image!: (?untyped) -> ::Image
  def location: () -> ::Location
  def location=: (::Location?) -> ::Location?
  def reload_location: () -> ::Location?
  def build_location: (?untyped) -> ::Location
  def create_location: (?untyped) -> ::Location
  def create_location!: (?untyped) -> ::Location

  module ::Locale::GeneratedAssociationMethods
  end
  include ::Locale::GeneratedAssociationMethods

  module ::Locale::GeneratedRelationMethods
  end

  class ::Locale::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Locale]
    include ::Locale::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Locale, ::String]
  end

  class ::Locale::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Locale]
    include ::Locale::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Locale, ::String]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Locale
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Locale]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Locale
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Locale]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Locale
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Locale]
    def reload: () -> ::Array[::Locale]

    def replace: (::Array[::Locale]) -> void
    def delete: (*::Locale | ::String) -> ::Array[::Locale]
    def destroy: (*::Locale | ::String) -> ::Array[::Locale]
    def <<: (*::Locale | ::Array[::Locale]) -> self
    def prepend: (*::Locale | ::Array[::Locale]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Venue < ::ApplicationRecord
end
class ::Venue::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Person < ::ApplicationRecord
end
class ::Person::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Event < ::ApplicationRecord
end
class ::Event::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Location < ::ApplicationRecord
end
class ::Location::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Image < ::ApplicationRecord
end
