# resolve-type-names: false

class ::Page < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Page, ::Page::ActiveRecord_Relation, ::String]

  module ::Page::GeneratedAttributeMethods
    def id: () -> ::String

    def id=: (::String) -> ::String

    def id?: () -> bool

    def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_change: () -> [ ::String?, ::String? ]

    def id_will_change!: () -> void

    def id_was: () -> ::String?

    def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_previous_change: () -> ::Array[::String?]?

    def id_previously_was: () -> ::String?

    def id_before_last_save: () -> ::String?

    def id_change_to_be_saved: () -> ::Array[::String?]?

    def id_in_database: () -> ::String?

    def saved_change_to_id: () -> ::Array[::String?]?

    def saved_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::String

    def id_for_database: () -> ::String

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time

    def image_id: () -> ::String?

    def image_id=: (::String?) -> ::String?

    def image_id?: () -> bool

    def image_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def image_id_change: () -> [ ::String?, ::String? ]

    def image_id_will_change!: () -> void

    def image_id_was: () -> ::String?

    def image_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def image_id_previous_change: () -> ::Array[::String?]?

    def image_id_previously_was: () -> ::String?

    def image_id_before_last_save: () -> ::String?

    def image_id_change_to_be_saved: () -> ::Array[::String?]?

    def image_id_in_database: () -> ::String?

    def saved_change_to_image_id: () -> ::Array[::String?]?

    def saved_change_to_image_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_image_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_image_id!: () -> void

    def clear_image_id_change: () -> void

    def image_id_before_type_cast: () -> ::String?

    def image_id_for_database: () -> ::String?

    def cover_image_id: () -> ::String?

    def cover_image_id=: (::String?) -> ::String?

    def cover_image_id?: () -> bool

    def cover_image_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def cover_image_id_change: () -> [ ::String?, ::String? ]

    def cover_image_id_will_change!: () -> void

    def cover_image_id_was: () -> ::String?

    def cover_image_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def cover_image_id_previous_change: () -> ::Array[::String?]?

    def cover_image_id_previously_was: () -> ::String?

    def cover_image_id_before_last_save: () -> ::String?

    def cover_image_id_change_to_be_saved: () -> ::Array[::String?]?

    def cover_image_id_in_database: () -> ::String?

    def saved_change_to_cover_image_id: () -> ::Array[::String?]?

    def saved_change_to_cover_image_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_cover_image_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_cover_image_id!: () -> void

    def clear_cover_image_id_change: () -> void

    def cover_image_id_before_type_cast: () -> ::String?

    def cover_image_id_for_database: () -> ::String?

    def name: () -> ::String

    def name=: (::String) -> ::String

    def name?: () -> bool

    def name_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def name_change: () -> [ ::String?, ::String? ]

    def name_will_change!: () -> void

    def name_was: () -> ::String?

    def name_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def name_previous_change: () -> ::Array[::String?]?

    def name_previously_was: () -> ::String?

    def name_before_last_save: () -> ::String?

    def name_change_to_be_saved: () -> ::Array[::String?]?

    def name_in_database: () -> ::String?

    def saved_change_to_name: () -> ::Array[::String?]?

    def saved_change_to_name?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_name?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_name!: () -> void

    def clear_name_change: () -> void

    def name_before_type_cast: () -> ::String

    def name_for_database: () -> ::String

    def name_override: () -> ::String?

    def name_override=: (::String?) -> ::String?

    def name_override?: () -> bool

    def name_override_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def name_override_change: () -> [ ::String?, ::String? ]

    def name_override_will_change!: () -> void

    def name_override_was: () -> ::String?

    def name_override_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def name_override_previous_change: () -> ::Array[::String?]?

    def name_override_previously_was: () -> ::String?

    def name_override_before_last_save: () -> ::String?

    def name_override_change_to_be_saved: () -> ::Array[::String?]?

    def name_override_in_database: () -> ::String?

    def saved_change_to_name_override: () -> ::Array[::String?]?

    def saved_change_to_name_override?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_name_override?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_name_override!: () -> void

    def clear_name_override_change: () -> void

    def name_override_before_type_cast: () -> ::String?

    def name_override_for_database: () -> ::String?

    def facebook_id: () -> ::Integer

    def facebook_id=: (::Integer) -> ::Integer

    def facebook_id?: () -> bool

    def facebook_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def facebook_id_change: () -> [ ::Integer?, ::Integer? ]

    def facebook_id_will_change!: () -> void

    def facebook_id_was: () -> ::Integer?

    def facebook_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def facebook_id_previous_change: () -> ::Array[::Integer?]?

    def facebook_id_previously_was: () -> ::Integer?

    def facebook_id_before_last_save: () -> ::Integer?

    def facebook_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def facebook_id_in_database: () -> ::Integer?

    def saved_change_to_facebook_id: () -> ::Array[::Integer?]?

    def saved_change_to_facebook_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_facebook_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_facebook_id!: () -> void

    def clear_facebook_id_change: () -> void

    def facebook_id_before_type_cast: () -> ::Integer

    def facebook_id_for_database: () -> ::Integer

    def facebook_graph: () -> untyped

    def facebook_graph=: (untyped) -> untyped

    def facebook_graph?: () -> bool

    def facebook_graph_changed?: (?from: untyped, ?to: untyped) -> bool

    def facebook_graph_change: () -> [ untyped, untyped ]

    def facebook_graph_will_change!: () -> void

    def facebook_graph_was: () -> untyped

    def facebook_graph_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    def facebook_graph_previous_change: () -> ::Array[untyped]?

    def facebook_graph_previously_was: () -> untyped

    def facebook_graph_before_last_save: () -> untyped

    def facebook_graph_change_to_be_saved: () -> ::Array[untyped]?

    def facebook_graph_in_database: () -> untyped

    def saved_change_to_facebook_graph: () -> ::Array[untyped]?

    def saved_change_to_facebook_graph?: (?from: untyped, ?to: untyped) -> bool

    def will_save_change_to_facebook_graph?: (?from: untyped, ?to: untyped) -> bool

    def restore_facebook_graph!: () -> void

    def clear_facebook_graph_change: () -> void

    def facebook_graph_before_type_cast: () -> untyped

    def facebook_graph_for_database: () -> untyped

    def facebook_access_token: () -> ::String?

    def facebook_access_token=: (::String?) -> ::String?

    def facebook_access_token?: () -> bool

    def facebook_access_token_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def facebook_access_token_change: () -> [ ::String?, ::String? ]

    def facebook_access_token_will_change!: () -> void

    def facebook_access_token_was: () -> ::String?

    def facebook_access_token_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def facebook_access_token_previous_change: () -> ::Array[::String?]?

    def facebook_access_token_previously_was: () -> ::String?

    def facebook_access_token_before_last_save: () -> ::String?

    def facebook_access_token_change_to_be_saved: () -> ::Array[::String?]?

    def facebook_access_token_in_database: () -> ::String?

    def saved_change_to_facebook_access_token: () -> ::Array[::String?]?

    def saved_change_to_facebook_access_token?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_facebook_access_token?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_facebook_access_token!: () -> void

    def clear_facebook_access_token_change: () -> void

    def facebook_access_token_before_type_cast: () -> ::String?

    def facebook_access_token_for_database: () -> ::String?

    def facets: () -> ::String?

    def facets=: (::String?) -> ::String?

    def facets?: () -> bool

    def facets_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def facets_change: () -> [ ::String?, ::String? ]

    def facets_will_change!: () -> void

    def facets_was: () -> ::String?

    def facets_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def facets_previous_change: () -> ::Array[::String?]?

    def facets_previously_was: () -> ::String?

    def facets_before_last_save: () -> ::String?

    def facets_change_to_be_saved: () -> ::Array[::String?]?

    def facets_in_database: () -> ::String?

    def saved_change_to_facets: () -> ::Array[::String?]?

    def saved_change_to_facets?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_facets?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_facets!: () -> void

    def clear_facets_change: () -> void

    def facets_before_type_cast: () -> ::String?

    def facets_for_database: () -> ::String?

    def requires_user_token: () -> bool

    def requires_user_token=: (bool) -> bool

    def requires_user_token?: () -> bool

    def requires_user_token_changed?: (?from: bool?, ?to: bool?) -> bool

    def requires_user_token_change: () -> [ bool?, bool? ]

    def requires_user_token_will_change!: () -> void

    def requires_user_token_was: () -> bool?

    def requires_user_token_previously_changed?: (?from: bool?, ?to: bool?) -> bool

    def requires_user_token_previous_change: () -> ::Array[bool?]?

    def requires_user_token_previously_was: () -> bool?

    def requires_user_token_before_last_save: () -> bool?

    def requires_user_token_change_to_be_saved: () -> ::Array[bool?]?

    def requires_user_token_in_database: () -> bool?

    def saved_change_to_requires_user_token: () -> ::Array[bool?]?

    def saved_change_to_requires_user_token?: (?from: bool?, ?to: bool?) -> bool

    def will_save_change_to_requires_user_token?: (?from: bool?, ?to: bool?) -> bool

    def restore_requires_user_token!: () -> void

    def clear_requires_user_token_change: () -> void

    def requires_user_token_before_type_cast: () -> bool

    def requires_user_token_for_database: () -> bool

    def hidden: () -> bool

    def hidden=: (bool) -> bool

    def hidden?: () -> bool

    def hidden_changed?: (?from: bool?, ?to: bool?) -> bool

    def hidden_change: () -> [ bool?, bool? ]

    def hidden_will_change!: () -> void

    def hidden_was: () -> bool?

    def hidden_previously_changed?: (?from: bool?, ?to: bool?) -> bool

    def hidden_previous_change: () -> ::Array[bool?]?

    def hidden_previously_was: () -> bool?

    def hidden_before_last_save: () -> bool?

    def hidden_change_to_be_saved: () -> ::Array[bool?]?

    def hidden_in_database: () -> bool?

    def saved_change_to_hidden: () -> ::Array[bool?]?

    def saved_change_to_hidden?: (?from: bool?, ?to: bool?) -> bool

    def will_save_change_to_hidden?: (?from: bool?, ?to: bool?) -> bool

    def restore_hidden!: () -> void

    def clear_hidden_change: () -> void

    def hidden_before_type_cast: () -> bool

    def hidden_for_database: () -> bool

    def last_update_error: () -> ::String?

    def last_update_error=: (::String?) -> ::String?

    def last_update_error?: () -> bool

    def last_update_error_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def last_update_error_change: () -> [ ::String?, ::String? ]

    def last_update_error_will_change!: () -> void

    def last_update_error_was: () -> ::String?

    def last_update_error_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def last_update_error_previous_change: () -> ::Array[::String?]?

    def last_update_error_previously_was: () -> ::String?

    def last_update_error_before_last_save: () -> ::String?

    def last_update_error_change_to_be_saved: () -> ::Array[::String?]?

    def last_update_error_in_database: () -> ::String?

    def saved_change_to_last_update_error: () -> ::Array[::String?]?

    def saved_change_to_last_update_error?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_last_update_error?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_last_update_error!: () -> void

    def clear_last_update_error_change: () -> void

    def last_update_error_before_type_cast: () -> ::String?

    def last_update_error_for_database: () -> ::String?
  end
  include ::Page::GeneratedAttributeMethods
  module ::Page::GeneratedAliasAttributeMethods
    include ::Page::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::Page::GeneratedAliasAttributeMethods
  def reviews: () -> ::Review::ActiveRecord_Associations_CollectionProxy
  def reviews=: (::Review::ActiveRecord_Associations_CollectionProxy | ::Array[::Review]) -> (::Review::ActiveRecord_Associations_CollectionProxy | ::Array[::Review])
  def review_ids: () -> ::Array[::String]
  def review_ids=: (::Array[::String]) -> ::Array[::String]
  def user_likes: () -> ::UserLike::ActiveRecord_Associations_CollectionProxy
  def user_likes=: (::UserLike::ActiveRecord_Associations_CollectionProxy | ::Array[::UserLike]) -> (::UserLike::ActiveRecord_Associations_CollectionProxy | ::Array[::UserLike])
  def user_like_ids: () -> ::Array[::String]
  def user_like_ids=: (::Array[::String]) -> ::Array[::String]
  def users: () -> ::User::ActiveRecord_Associations_CollectionProxy
  def users=: (::User::ActiveRecord_Associations_CollectionProxy | ::Array[::User]) -> (::User::ActiveRecord_Associations_CollectionProxy | ::Array[::User])
  def user_ids: () -> ::Array[::String]
  def user_ids=: (::Array[::String]) -> ::Array[::String]
  def events: () -> ::Event::ActiveRecord_Associations_CollectionProxy
  def events=: (::Event::ActiveRecord_Associations_CollectionProxy | ::Array[::Event]) -> (::Event::ActiveRecord_Associations_CollectionProxy | ::Array[::Event])
  def event_ids: () -> ::Array[::String]
  def event_ids=: (::Array[::String]) -> ::Array[::String]

  def venue: () -> ::Venue?
  def venue=: (::Venue?) -> ::Venue?
  def build_venue: (?untyped) -> ::Venue
  def create_venue: (?untyped) -> ::Venue
  def create_venue!: (?untyped) -> ::Venue
  def reload_venue: () -> ::Venue?
  def person: () -> ::Person?
  def person=: (::Person?) -> ::Person?
  def build_person: (?untyped) -> ::Person
  def create_person: (?untyped) -> ::Person
  def create_person!: (?untyped) -> ::Person
  def reload_person: () -> ::Person?
  def photo_take: () -> ::PhotoTake
  def photo_take=: (::PhotoTake?) -> ::PhotoTake?
  def reload_photo_take: () -> ::PhotoTake?
  def build_photo_take: (?untyped) -> ::PhotoTake
  def create_photo_take: (?untyped) -> ::PhotoTake
  def create_photo_take!: (?untyped) -> ::PhotoTake
  def cover_photo: () -> ::PhotoTake
  def cover_photo=: (::PhotoTake?) -> ::PhotoTake?
  def reload_cover_photo: () -> ::PhotoTake?
  def build_cover_photo: (?untyped) -> ::PhotoTake
  def create_cover_photo: (?untyped) -> ::PhotoTake
  def create_cover_photo!: (?untyped) -> ::PhotoTake

  module ::Page::GeneratedAssociationMethods
  end
  include ::Page::GeneratedAssociationMethods

  module ::Page::GeneratedRelationMethods
  end

  class ::Page::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Page]
    include ::Page::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Page, ::String]
  end

  class ::Page::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Page]
    include ::Page::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Page, ::String]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Page
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Page]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Page
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Page]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Page
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Page]
    def reload: () -> ::Array[::Page]

    def replace: (::Array[::Page]) -> void
    def delete: (*::Page | ::String) -> ::Array[::Page]
    def destroy: (*::Page | ::String) -> ::Array[::Page]
    def <<: (*::Page | ::Array[::Page]) -> self
    def prepend: (*::Page | ::Array[::Page]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Review < ::ApplicationRecord
end
class ::Review::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::UserLike < ::ApplicationRecord
end
class ::UserLike::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::User < ::ApplicationRecord
end
class ::User::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Event < ::ApplicationRecord
end
class ::Event::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Venue < ::ApplicationRecord
end
class ::Person < ::ApplicationRecord
end
class ::PhotoTake < ::ApplicationRecord
end
