# resolve-type-names: false

class ::Person < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Person, ::Person::ActiveRecord_Relation, ::String]

  module ::Person::GeneratedAttributeMethods
    def id: () -> ::String

    def id=: (::String) -> ::String

    def id?: () -> bool

    def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_change: () -> [ ::String?, ::String? ]

    def id_will_change!: () -> void

    def id_was: () -> ::String?

    def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_previous_change: () -> ::Array[::String?]?

    def id_previously_was: () -> ::String?

    def id_before_last_save: () -> ::String?

    def id_change_to_be_saved: () -> ::Array[::String?]?

    def id_in_database: () -> ::String?

    def saved_change_to_id: () -> ::Array[::String?]?

    def saved_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::String

    def id_for_database: () -> ::String

    def arc_face_embedding: () -> untyped

    def arc_face_embedding=: (untyped) -> untyped

    def arc_face_embedding?: () -> bool

    def arc_face_embedding_changed?: (?from: untyped, ?to: untyped) -> bool

    def arc_face_embedding_change: () -> [ untyped, untyped ]

    def arc_face_embedding_will_change!: () -> void

    def arc_face_embedding_was: () -> untyped

    def arc_face_embedding_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    def arc_face_embedding_previous_change: () -> ::Array[untyped]?

    def arc_face_embedding_previously_was: () -> untyped

    def arc_face_embedding_before_last_save: () -> untyped

    def arc_face_embedding_change_to_be_saved: () -> ::Array[untyped]?

    def arc_face_embedding_in_database: () -> untyped

    def saved_change_to_arc_face_embedding: () -> ::Array[untyped]?

    def saved_change_to_arc_face_embedding?: (?from: untyped, ?to: untyped) -> bool

    def will_save_change_to_arc_face_embedding?: (?from: untyped, ?to: untyped) -> bool

    def restore_arc_face_embedding!: () -> void

    def clear_arc_face_embedding_change: () -> void

    def arc_face_embedding_before_type_cast: () -> untyped?

    def arc_face_embedding_for_database: () -> untyped?

    def cluster_number: () -> ::Integer?

    def cluster_number=: (::Integer?) -> ::Integer?

    def cluster_number?: () -> bool

    def cluster_number_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def cluster_number_change: () -> [ ::Integer?, ::Integer? ]

    def cluster_number_will_change!: () -> void

    def cluster_number_was: () -> ::Integer?

    def cluster_number_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def cluster_number_previous_change: () -> ::Array[::Integer?]?

    def cluster_number_previously_was: () -> ::Integer?

    def cluster_number_before_last_save: () -> ::Integer?

    def cluster_number_change_to_be_saved: () -> ::Array[::Integer?]?

    def cluster_number_in_database: () -> ::Integer?

    def saved_change_to_cluster_number: () -> ::Array[::Integer?]?

    def saved_change_to_cluster_number?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_cluster_number?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_cluster_number!: () -> void

    def clear_cluster_number_change: () -> void

    def cluster_number_before_type_cast: () -> ::Integer?

    def cluster_number_for_database: () -> ::Integer?

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def email: () -> ::String?

    def email=: (::String?) -> ::String?

    def email?: () -> bool

    def email_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def email_change: () -> [ ::String?, ::String? ]

    def email_will_change!: () -> void

    def email_was: () -> ::String?

    def email_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def email_previous_change: () -> ::Array[::String?]?

    def email_previously_was: () -> ::String?

    def email_before_last_save: () -> ::String?

    def email_change_to_be_saved: () -> ::Array[::String?]?

    def email_in_database: () -> ::String?

    def saved_change_to_email: () -> ::Array[::String?]?

    def saved_change_to_email?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_email?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_email!: () -> void

    def clear_email_change: () -> void

    def email_before_type_cast: () -> ::String?

    def email_for_database: () -> ::String?

    def facebook_id: () -> ::String?

    def facebook_id=: (::String?) -> ::String?

    def facebook_id?: () -> bool

    def facebook_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def facebook_id_change: () -> [ ::String?, ::String? ]

    def facebook_id_will_change!: () -> void

    def facebook_id_was: () -> ::String?

    def facebook_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def facebook_id_previous_change: () -> ::Array[::String?]?

    def facebook_id_previously_was: () -> ::String?

    def facebook_id_before_last_save: () -> ::String?

    def facebook_id_change_to_be_saved: () -> ::Array[::String?]?

    def facebook_id_in_database: () -> ::String?

    def saved_change_to_facebook_id: () -> ::Array[::String?]?

    def saved_change_to_facebook_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_facebook_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_facebook_id!: () -> void

    def clear_facebook_id_change: () -> void

    def facebook_id_before_type_cast: () -> ::String?

    def facebook_id_for_database: () -> ::String?

    def first_name: () -> ::String?

    def first_name=: (::String?) -> ::String?

    def first_name?: () -> bool

    def first_name_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def first_name_change: () -> [ ::String?, ::String? ]

    def first_name_will_change!: () -> void

    def first_name_was: () -> ::String?

    def first_name_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def first_name_previous_change: () -> ::Array[::String?]?

    def first_name_previously_was: () -> ::String?

    def first_name_before_last_save: () -> ::String?

    def first_name_change_to_be_saved: () -> ::Array[::String?]?

    def first_name_in_database: () -> ::String?

    def saved_change_to_first_name: () -> ::Array[::String?]?

    def saved_change_to_first_name?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_first_name?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_first_name!: () -> void

    def clear_first_name_change: () -> void

    def first_name_before_type_cast: () -> ::String?

    def first_name_for_database: () -> ::String?

    def instagram_id: () -> ::String?

    def instagram_id=: (::String?) -> ::String?

    def instagram_id?: () -> bool

    def instagram_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def instagram_id_change: () -> [ ::String?, ::String? ]

    def instagram_id_will_change!: () -> void

    def instagram_id_was: () -> ::String?

    def instagram_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def instagram_id_previous_change: () -> ::Array[::String?]?

    def instagram_id_previously_was: () -> ::String?

    def instagram_id_before_last_save: () -> ::String?

    def instagram_id_change_to_be_saved: () -> ::Array[::String?]?

    def instagram_id_in_database: () -> ::String?

    def saved_change_to_instagram_id: () -> ::Array[::String?]?

    def saved_change_to_instagram_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_instagram_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_instagram_id!: () -> void

    def clear_instagram_id_change: () -> void

    def instagram_id_before_type_cast: () -> ::String?

    def instagram_id_for_database: () -> ::String?

    def last_name: () -> ::String?

    def last_name=: (::String?) -> ::String?

    def last_name?: () -> bool

    def last_name_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def last_name_change: () -> [ ::String?, ::String? ]

    def last_name_will_change!: () -> void

    def last_name_was: () -> ::String?

    def last_name_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def last_name_previous_change: () -> ::Array[::String?]?

    def last_name_previously_was: () -> ::String?

    def last_name_before_last_save: () -> ::String?

    def last_name_change_to_be_saved: () -> ::Array[::String?]?

    def last_name_in_database: () -> ::String?

    def saved_change_to_last_name: () -> ::Array[::String?]?

    def saved_change_to_last_name?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_last_name?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_last_name!: () -> void

    def clear_last_name_change: () -> void

    def last_name_before_type_cast: () -> ::String?

    def last_name_for_database: () -> ::String?

    def name: () -> ::String?

    def name=: (::String?) -> ::String?

    def name?: () -> bool

    def name_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def name_change: () -> [ ::String?, ::String? ]

    def name_will_change!: () -> void

    def name_was: () -> ::String?

    def name_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def name_previous_change: () -> ::Array[::String?]?

    def name_previously_was: () -> ::String?

    def name_before_last_save: () -> ::String?

    def name_change_to_be_saved: () -> ::Array[::String?]?

    def name_in_database: () -> ::String?

    def saved_change_to_name: () -> ::Array[::String?]?

    def saved_change_to_name?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_name?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_name!: () -> void

    def clear_name_change: () -> void

    def name_before_type_cast: () -> ::String?

    def name_for_database: () -> ::String?

    def photographer_id: () -> ::String

    def photographer_id=: (::String) -> ::String

    def photographer_id?: () -> bool

    def photographer_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def photographer_id_change: () -> [ ::String?, ::String? ]

    def photographer_id_will_change!: () -> void

    def photographer_id_was: () -> ::String?

    def photographer_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def photographer_id_previous_change: () -> ::Array[::String?]?

    def photographer_id_previously_was: () -> ::String?

    def photographer_id_before_last_save: () -> ::String?

    def photographer_id_change_to_be_saved: () -> ::Array[::String?]?

    def photographer_id_in_database: () -> ::String?

    def saved_change_to_photographer_id: () -> ::Array[::String?]?

    def saved_change_to_photographer_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_photographer_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_photographer_id!: () -> void

    def clear_photographer_id_change: () -> void

    def photographer_id_before_type_cast: () -> ::String

    def photographer_id_for_database: () -> ::String

    def twitter_id: () -> ::String?

    def twitter_id=: (::String?) -> ::String?

    def twitter_id?: () -> bool

    def twitter_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def twitter_id_change: () -> [ ::String?, ::String? ]

    def twitter_id_will_change!: () -> void

    def twitter_id_was: () -> ::String?

    def twitter_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def twitter_id_previous_change: () -> ::Array[::String?]?

    def twitter_id_previously_was: () -> ::String?

    def twitter_id_before_last_save: () -> ::String?

    def twitter_id_change_to_be_saved: () -> ::Array[::String?]?

    def twitter_id_in_database: () -> ::String?

    def saved_change_to_twitter_id: () -> ::Array[::String?]?

    def saved_change_to_twitter_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_twitter_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_twitter_id!: () -> void

    def clear_twitter_id_change: () -> void

    def twitter_id_before_type_cast: () -> ::String?

    def twitter_id_for_database: () -> ::String?

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time
  end
  include ::Person::GeneratedAttributeMethods
  module ::Person::GeneratedAliasAttributeMethods
    include ::Person::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::Person::GeneratedAliasAttributeMethods
  def photo_people: () -> ::PhotoPerson::ActiveRecord_Associations_CollectionProxy
  def photo_people=: (::PhotoPerson::ActiveRecord_Associations_CollectionProxy | ::Array[::PhotoPerson]) -> (::PhotoPerson::ActiveRecord_Associations_CollectionProxy | ::Array[::PhotoPerson])
  def photo_person_ids: () -> ::Array[::String]
  def photo_person_ids=: (::Array[::String]) -> ::Array[::String]
  def photos: () -> ::Photo::ActiveRecord_Associations_CollectionProxy
  def photos=: (::Photo::ActiveRecord_Associations_CollectionProxy | ::Array[::Photo]) -> (::Photo::ActiveRecord_Associations_CollectionProxy | ::Array[::Photo])
  def photo_ids: () -> ::Array[::String]
  def photo_ids=: (::Array[::String]) -> ::Array[::String]

  def photographer: () -> ::Photographer
  def photographer=: (::Photographer?) -> ::Photographer?
  def reload_photographer: () -> ::Photographer?
  def build_photographer: (?untyped) -> ::Photographer
  def create_photographer: (?untyped) -> ::Photographer
  def create_photographer!: (?untyped) -> ::Photographer

  module ::Person::GeneratedAssociationMethods
  end
  include ::Person::GeneratedAssociationMethods

  def self.for_photographer: (untyped photographer) -> ::Person::ActiveRecord_Relation
  def self.with_embedding: () -> ::Person::ActiveRecord_Relation

  module ::Person::GeneratedRelationMethods
    def for_photographer: (untyped photographer) -> ::Person::ActiveRecord_Relation

    def with_embedding: () -> ::Person::ActiveRecord_Relation
  end

  class ::Person::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Person]
    include ::Person::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Person, ::String]
  end

  class ::Person::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Person]
    include ::Person::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Person, ::String]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Person
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Person]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Person
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Person]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Person
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Person]
    def reload: () -> ::Array[::Person]

    def replace: (::Array[::Person]) -> void
    def delete: (*::Person | ::String) -> ::Array[::Person]
    def destroy: (*::Person | ::String) -> ::Array[::Person]
    def <<: (*::Person | ::Array[::Person]) -> self
    def prepend: (*::Person | ::Array[::Person]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::PhotoPerson < ::ApplicationRecord
end
class ::PhotoPerson::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Photo < ::ApplicationRecord
end
class ::Photo::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Photographer < ::ApplicationRecord
end
