# resolve-type-names: false

class ::Person < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Person, ::Person::ActiveRecord_Relation, ::String]

  module ::Person::GeneratedAttributeMethods
    def id: () -> ::String

    def id=: (::String) -> ::String

    def id?: () -> bool

    def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_change: () -> [ ::String?, ::String? ]

    def id_will_change!: () -> void

    def id_was: () -> ::String?

    def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_previous_change: () -> ::Array[::String?]?

    def id_previously_was: () -> ::String?

    def id_before_last_save: () -> ::String?

    def id_change_to_be_saved: () -> ::Array[::String?]?

    def id_in_database: () -> ::String?

    def saved_change_to_id: () -> ::Array[::String?]?

    def saved_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::String

    def id_for_database: () -> ::String

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time

    def audience_id: () -> ::String

    def audience_id=: (::String) -> ::String

    def audience_id?: () -> bool

    def audience_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def audience_id_change: () -> [ ::String?, ::String? ]

    def audience_id_will_change!: () -> void

    def audience_id_was: () -> ::String?

    def audience_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def audience_id_previous_change: () -> ::Array[::String?]?

    def audience_id_previously_was: () -> ::String?

    def audience_id_before_last_save: () -> ::String?

    def audience_id_change_to_be_saved: () -> ::Array[::String?]?

    def audience_id_in_database: () -> ::String?

    def saved_change_to_audience_id: () -> ::Array[::String?]?

    def saved_change_to_audience_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_audience_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_audience_id!: () -> void

    def clear_audience_id_change: () -> void

    def audience_id_before_type_cast: () -> ::String

    def audience_id_for_database: () -> ::String

    def page_id: () -> ::String

    def page_id=: (::String) -> ::String

    def page_id?: () -> bool

    def page_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def page_id_change: () -> [ ::String?, ::String? ]

    def page_id_will_change!: () -> void

    def page_id_was: () -> ::String?

    def page_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def page_id_previous_change: () -> ::Array[::String?]?

    def page_id_previously_was: () -> ::String?

    def page_id_before_last_save: () -> ::String?

    def page_id_change_to_be_saved: () -> ::Array[::String?]?

    def page_id_in_database: () -> ::String?

    def saved_change_to_page_id: () -> ::Array[::String?]?

    def saved_change_to_page_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_page_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_page_id!: () -> void

    def clear_page_id_change: () -> void

    def page_id_before_type_cast: () -> ::String

    def page_id_for_database: () -> ::String

    def order: () -> ::Integer

    def order=: (::Integer) -> ::Integer

    def order?: () -> bool

    def order_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def order_change: () -> [ ::Integer?, ::Integer? ]

    def order_will_change!: () -> void

    def order_was: () -> ::Integer?

    def order_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def order_previous_change: () -> ::Array[::Integer?]?

    def order_previously_was: () -> ::Integer?

    def order_before_last_save: () -> ::Integer?

    def order_change_to_be_saved: () -> ::Array[::Integer?]?

    def order_in_database: () -> ::Integer?

    def saved_change_to_order: () -> ::Array[::Integer?]?

    def saved_change_to_order?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_order?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_order!: () -> void

    def clear_order_change: () -> void

    def order_before_type_cast: () -> ::Integer

    def order_for_database: () -> ::Integer

    def global: () -> bool

    def global=: (bool) -> bool

    def global?: () -> bool

    def global_changed?: (?from: bool?, ?to: bool?) -> bool

    def global_change: () -> [ bool?, bool? ]

    def global_will_change!: () -> void

    def global_was: () -> bool?

    def global_previously_changed?: (?from: bool?, ?to: bool?) -> bool

    def global_previous_change: () -> ::Array[bool?]?

    def global_previously_was: () -> bool?

    def global_before_last_save: () -> bool?

    def global_change_to_be_saved: () -> ::Array[bool?]?

    def global_in_database: () -> bool?

    def saved_change_to_global: () -> ::Array[bool?]?

    def saved_change_to_global?: (?from: bool?, ?to: bool?) -> bool

    def will_save_change_to_global?: (?from: bool?, ?to: bool?) -> bool

    def restore_global!: () -> void

    def clear_global_change: () -> void

    def global_before_type_cast: () -> bool

    def global_for_database: () -> bool

    def like_required: () -> bool

    def like_required=: (bool) -> bool

    def like_required?: () -> bool

    def like_required_changed?: (?from: bool?, ?to: bool?) -> bool

    def like_required_change: () -> [ bool?, bool? ]

    def like_required_will_change!: () -> void

    def like_required_was: () -> bool?

    def like_required_previously_changed?: (?from: bool?, ?to: bool?) -> bool

    def like_required_previous_change: () -> ::Array[bool?]?

    def like_required_previously_was: () -> bool?

    def like_required_before_last_save: () -> bool?

    def like_required_change_to_be_saved: () -> ::Array[bool?]?

    def like_required_in_database: () -> bool?

    def saved_change_to_like_required: () -> ::Array[bool?]?

    def saved_change_to_like_required?: (?from: bool?, ?to: bool?) -> bool

    def will_save_change_to_like_required?: (?from: bool?, ?to: bool?) -> bool

    def restore_like_required!: () -> void

    def clear_like_required_change: () -> void

    def like_required_before_type_cast: () -> bool

    def like_required_for_database: () -> bool
  end
  include ::Person::GeneratedAttributeMethods
  module ::Person::GeneratedAliasAttributeMethods
    include ::Person::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::Person::GeneratedAliasAttributeMethods
  def event_people: () -> ::EventPerson::ActiveRecord_Associations_CollectionProxy
  def event_people=: (::EventPerson::ActiveRecord_Associations_CollectionProxy | ::Array[::EventPerson]) -> (::EventPerson::ActiveRecord_Associations_CollectionProxy | ::Array[::EventPerson])
  def event_person_ids: () -> ::Array[::String]
  def event_person_ids=: (::Array[::String]) -> ::Array[::String]
  def events: () -> ::Event::ActiveRecord_Associations_CollectionProxy
  def events=: (::Event::ActiveRecord_Associations_CollectionProxy | ::Array[::Event]) -> (::Event::ActiveRecord_Associations_CollectionProxy | ::Array[::Event])
  def event_ids: () -> ::Array[::String]
  def event_ids=: (::Array[::String]) -> ::Array[::String]

  def page: () -> ::Page
  def page=: (::Page?) -> ::Page?
  def reload_page: () -> ::Page?
  def build_page: (?untyped) -> ::Page
  def create_page: (?untyped) -> ::Page
  def create_page!: (?untyped) -> ::Page

  module ::Person::GeneratedAssociationMethods
  end
  include ::Person::GeneratedAssociationMethods

  module ::Person::GeneratedRelationMethods
  end

  class ::Person::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Person]
    include ::Person::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Person, ::String]
  end

  class ::Person::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Person]
    include ::Person::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Person, ::String]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Person
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Person]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Person
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Person]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Person
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Person]
    def reload: () -> ::Array[::Person]

    def replace: (::Array[::Person]) -> void
    def delete: (*::Person | ::String) -> ::Array[::Person]
    def destroy: (*::Person | ::String) -> ::Array[::Person]
    def <<: (*::Person | ::Array[::Person]) -> self
    def prepend: (*::Person | ::Array[::Person]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::EventPerson < ::ApplicationRecord
end
class ::EventPerson::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Event < ::ApplicationRecord
end
class ::Event::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Page < ::ApplicationRecord
end
