# resolve-type-names: false

class ::PhotoPerson < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::PhotoPerson, ::PhotoPerson::ActiveRecord_Relation, ::String]

  module ::PhotoPerson::GeneratedAttributeMethods
    def id: () -> ::String

    def id=: (::String) -> ::String

    def id?: () -> bool

    def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_change: () -> [::String?, ::String?]

    def id_will_change!: () -> void

    def id_was: () -> ::String?

    def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_previous_change: () -> ::Array[::String?]?

    def id_previously_was: () -> ::String?

    def id_before_last_save: () -> ::String?

    def id_change_to_be_saved: () -> ::Array[::String?]?

    def id_in_database: () -> ::String?

    def saved_change_to_id: () -> ::Array[::String?]?

    def saved_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::String

    def id_for_database: () -> ::String

    def arc_face_embedding: () -> untyped

    def arc_face_embedding=: (untyped) -> untyped

    def arc_face_embedding?: () -> bool

    def arc_face_embedding_changed?: (?from: untyped, ?to: untyped) -> bool

    def arc_face_embedding_change: () -> [untyped, untyped]

    def arc_face_embedding_will_change!: () -> void

    def arc_face_embedding_was: () -> untyped

    def arc_face_embedding_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    def arc_face_embedding_previous_change: () -> ::Array[untyped]?

    def arc_face_embedding_previously_was: () -> untyped

    def arc_face_embedding_before_last_save: () -> untyped

    def arc_face_embedding_change_to_be_saved: () -> ::Array[untyped]?

    def arc_face_embedding_in_database: () -> untyped

    def saved_change_to_arc_face_embedding: () -> ::Array[untyped]?

    def saved_change_to_arc_face_embedding?: (?from: untyped, ?to: untyped) -> bool

    def will_save_change_to_arc_face_embedding?: (?from: untyped, ?to: untyped) -> bool

    def restore_arc_face_embedding!: () -> void

    def clear_arc_face_embedding_change: () -> void

    def arc_face_embedding_before_type_cast: () -> untyped?

    def arc_face_embedding_for_database: () -> untyped?

    def bounding_box: () -> untyped

    def bounding_box=: (untyped) -> untyped

    def bounding_box?: () -> bool

    def bounding_box_changed?: (?from: untyped, ?to: untyped) -> bool

    def bounding_box_change: () -> [untyped, untyped]

    def bounding_box_will_change!: () -> void

    def bounding_box_was: () -> untyped

    def bounding_box_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    def bounding_box_previous_change: () -> ::Array[untyped]?

    def bounding_box_previously_was: () -> untyped

    def bounding_box_before_last_save: () -> untyped

    def bounding_box_change_to_be_saved: () -> ::Array[untyped]?

    def bounding_box_in_database: () -> untyped

    def saved_change_to_bounding_box: () -> ::Array[untyped]?

    def saved_change_to_bounding_box?: (?from: untyped, ?to: untyped) -> bool

    def will_save_change_to_bounding_box?: (?from: untyped, ?to: untyped) -> bool

    def restore_bounding_box!: () -> void

    def clear_bounding_box_change: () -> void

    def bounding_box_before_type_cast: () -> untyped

    def bounding_box_for_database: () -> untyped

    def cluster_number: () -> ::Integer?

    def cluster_number=: (::Integer?) -> ::Integer?

    def cluster_number?: () -> bool

    def cluster_number_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def cluster_number_change: () -> [::Integer?, ::Integer?]

    def cluster_number_will_change!: () -> void

    def cluster_number_was: () -> ::Integer?

    def cluster_number_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def cluster_number_previous_change: () -> ::Array[::Integer?]?

    def cluster_number_previously_was: () -> ::Integer?

    def cluster_number_before_last_save: () -> ::Integer?

    def cluster_number_change_to_be_saved: () -> ::Array[::Integer?]?

    def cluster_number_in_database: () -> ::Integer?

    def saved_change_to_cluster_number: () -> ::Array[::Integer?]?

    def saved_change_to_cluster_number?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_cluster_number?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_cluster_number!: () -> void

    def clear_cluster_number_change: () -> void

    def cluster_number_before_type_cast: () -> ::Integer?

    def cluster_number_for_database: () -> ::Integer?

    def confidence: () -> ::Float?

    def confidence=: (::Float?) -> ::Float?

    def confidence?: () -> bool

    def confidence_changed?: (?from: ::Float?, ?to: ::Float?) -> bool

    def confidence_change: () -> [::Float?, ::Float?]

    def confidence_will_change!: () -> void

    def confidence_was: () -> ::Float?

    def confidence_previously_changed?: (?from: ::Float?, ?to: ::Float?) -> bool

    def confidence_previous_change: () -> ::Array[::Float?]?

    def confidence_previously_was: () -> ::Float?

    def confidence_before_last_save: () -> ::Float?

    def confidence_change_to_be_saved: () -> ::Array[::Float?]?

    def confidence_in_database: () -> ::Float?

    def saved_change_to_confidence: () -> ::Array[::Float?]?

    def saved_change_to_confidence?: (?from: ::Float?, ?to: ::Float?) -> bool

    def will_save_change_to_confidence?: (?from: ::Float?, ?to: ::Float?) -> bool

    def restore_confidence!: () -> void

    def clear_confidence_change: () -> void

    def confidence_before_type_cast: () -> ::Float?

    def confidence_for_database: () -> ::Float?

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone?]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def person_id: () -> ::String?

    def person_id=: (::String?) -> ::String?

    def person_id?: () -> bool

    def person_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def person_id_change: () -> [::String?, ::String?]

    def person_id_will_change!: () -> void

    def person_id_was: () -> ::String?

    def person_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def person_id_previous_change: () -> ::Array[::String?]?

    def person_id_previously_was: () -> ::String?

    def person_id_before_last_save: () -> ::String?

    def person_id_change_to_be_saved: () -> ::Array[::String?]?

    def person_id_in_database: () -> ::String?

    def saved_change_to_person_id: () -> ::Array[::String?]?

    def saved_change_to_person_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_person_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_person_id!: () -> void

    def clear_person_id_change: () -> void

    def person_id_before_type_cast: () -> ::String?

    def person_id_for_database: () -> ::String?

    def photo_id: () -> ::String

    def photo_id=: (::String) -> ::String

    def photo_id?: () -> bool

    def photo_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def photo_id_change: () -> [::String?, ::String?]

    def photo_id_will_change!: () -> void

    def photo_id_was: () -> ::String?

    def photo_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def photo_id_previous_change: () -> ::Array[::String?]?

    def photo_id_previously_was: () -> ::String?

    def photo_id_before_last_save: () -> ::String?

    def photo_id_change_to_be_saved: () -> ::Array[::String?]?

    def photo_id_in_database: () -> ::String?

    def saved_change_to_photo_id: () -> ::Array[::String?]?

    def saved_change_to_photo_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_photo_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_photo_id!: () -> void

    def clear_photo_id_change: () -> void

    def photo_id_before_type_cast: () -> ::String

    def photo_id_for_database: () -> ::String

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone?]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time
  end

  include ::PhotoPerson::GeneratedAttributeMethods

  module ::PhotoPerson::GeneratedAliasAttributeMethods
    include ::PhotoPerson::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end

  include ::PhotoPerson::GeneratedAliasAttributeMethods

  def face_image_attachment: () -> ::ActiveStorage::Attachment?

  def face_image_attachment=: (::ActiveStorage::Attachment?) -> ::ActiveStorage::Attachment?

  def build_face_image_attachment: (?untyped) -> ::ActiveStorage::Attachment

  def create_face_image_attachment: (?untyped) -> ::ActiveStorage::Attachment

  def create_face_image_attachment!: (?untyped) -> ::ActiveStorage::Attachment

  def reload_face_image_attachment: () -> ::ActiveStorage::Attachment?

  def face_image_blob: () -> ::ActiveStorage::Blob?

  def face_image_blob=: (::ActiveStorage::Blob?) -> ::ActiveStorage::Blob?

  def build_face_image_blob: (?untyped) -> ::ActiveStorage::Blob

  def create_face_image_blob: (?untyped) -> ::ActiveStorage::Blob

  def create_face_image_blob!: (?untyped) -> ::ActiveStorage::Blob

  def reload_face_image_blob: () -> ::ActiveStorage::Blob?

  def photo: () -> ::Photo

  def photo=: (::Photo?) -> ::Photo?

  def reload_photo: () -> ::Photo?

  def build_photo: (?untyped) -> ::Photo

  def create_photo: (?untyped) -> ::Photo

  def create_photo!: (?untyped) -> ::Photo

  def person: () -> ::Person?

  def person=: (::Person?) -> ::Person?

  def reload_person: () -> ::Person?

  def build_person: (?untyped) -> ::Person

  def create_person: (?untyped) -> ::Person

  def create_person!: (?untyped) -> ::Person

  module ::PhotoPerson::GeneratedAssociationMethods
    def face_image: () -> ::ActiveStorage::Attached::One

    def face_image=: (::ActionDispatch::Http::UploadedFile) -> ::ActionDispatch::Http::UploadedFile
      | (::Rack::Test::UploadedFile) -> ::Rack::Test::UploadedFile
      | (::ActiveStorage::Blob) -> ::ActiveStorage::Blob
      | (::String) -> ::String
      | ({ io: ::IO, filename: ::String, content_type: ::String? }) -> { io: ::IO, filename: ::String, content_type: ::String? }
      | (nil) -> nil
  end

  include ::PhotoPerson::GeneratedAssociationMethods

  def self.with_attached_face_image: () -> ::PhotoPerson::ActiveRecord_Relation

  module ::PhotoPerson::GeneratedRelationMethods
    def with_attached_face_image: () -> ::PhotoPerson::ActiveRecord_Relation
  end

  class ::PhotoPerson::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::PhotoPerson]
    include ::PhotoPerson::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::PhotoPerson, ::String]
  end

  class ::PhotoPerson::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::PhotoPerson]
    include ::PhotoPerson::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::PhotoPerson, ::String]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::PhotoPerson
      | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::PhotoPerson]

    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::PhotoPerson
      | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::PhotoPerson]

    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::PhotoPerson
      | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::PhotoPerson]

    def reload: () -> ::Array[::PhotoPerson]

    def replace: (::Array[::PhotoPerson]) -> void

    def delete: (*::PhotoPerson | ::String) -> ::Array[::PhotoPerson]

    def destroy: (*::PhotoPerson | ::String) -> ::Array[::PhotoPerson]

    def <<: (*::PhotoPerson | ::Array[::PhotoPerson]) -> self

    def prepend: (*::PhotoPerson | ::Array[::PhotoPerson]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end

class ::Photo < ::ApplicationRecord
end

class ::Person < ::ApplicationRecord
end
