# resolve-type-names: false

class ::Review < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Review, ::Review::ActiveRecord_Relation, ::String]

  module ::Review::GeneratedAttributeMethods
    def id: () -> ::String

    def id=: (::String) -> ::String

    def id?: () -> bool

    def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_change: () -> [ ::String?, ::String? ]

    def id_will_change!: () -> void

    def id_was: () -> ::String?

    def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_previous_change: () -> ::Array[::String?]?

    def id_previously_was: () -> ::String?

    def id_before_last_save: () -> ::String?

    def id_change_to_be_saved: () -> ::Array[::String?]?

    def id_in_database: () -> ::String?

    def saved_change_to_id: () -> ::Array[::String?]?

    def saved_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::String

    def id_for_database: () -> ::String

    def content: () -> ::String

    def content=: (::String) -> ::String

    def content?: () -> bool

    def content_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def content_change: () -> [ ::String?, ::String? ]

    def content_will_change!: () -> void

    def content_was: () -> ::String?

    def content_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def content_previous_change: () -> ::Array[::String?]?

    def content_previously_was: () -> ::String?

    def content_before_last_save: () -> ::String?

    def content_change_to_be_saved: () -> ::Array[::String?]?

    def content_in_database: () -> ::String?

    def saved_change_to_content: () -> ::Array[::String?]?

    def saved_change_to_content?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_content?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_content!: () -> void

    def clear_content_change: () -> void

    def content_before_type_cast: () -> ::String

    def content_for_database: () -> ::String

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def page_id: () -> ::String

    def page_id=: (::String) -> ::String

    def page_id?: () -> bool

    def page_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def page_id_change: () -> [ ::String?, ::String? ]

    def page_id_will_change!: () -> void

    def page_id_was: () -> ::String?

    def page_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def page_id_previous_change: () -> ::Array[::String?]?

    def page_id_previously_was: () -> ::String?

    def page_id_before_last_save: () -> ::String?

    def page_id_change_to_be_saved: () -> ::Array[::String?]?

    def page_id_in_database: () -> ::String?

    def saved_change_to_page_id: () -> ::Array[::String?]?

    def saved_change_to_page_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_page_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_page_id!: () -> void

    def clear_page_id_change: () -> void

    def page_id_before_type_cast: () -> ::String

    def page_id_for_database: () -> ::String

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time

    def user_id: () -> ::String

    def user_id=: (::String) -> ::String

    def user_id?: () -> bool

    def user_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def user_id_change: () -> [ ::String?, ::String? ]

    def user_id_will_change!: () -> void

    def user_id_was: () -> ::String?

    def user_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def user_id_previous_change: () -> ::Array[::String?]?

    def user_id_previously_was: () -> ::String?

    def user_id_before_last_save: () -> ::String?

    def user_id_change_to_be_saved: () -> ::Array[::String?]?

    def user_id_in_database: () -> ::String?

    def saved_change_to_user_id: () -> ::Array[::String?]?

    def saved_change_to_user_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_user_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_user_id!: () -> void

    def clear_user_id_change: () -> void

    def user_id_before_type_cast: () -> ::String

    def user_id_for_database: () -> ::String
  end
  include ::Review::GeneratedAttributeMethods
  module ::Review::GeneratedAliasAttributeMethods
    include ::Review::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::Review::GeneratedAliasAttributeMethods

  def page: () -> ::Page
  def page=: (::Page?) -> ::Page?
  def reload_page: () -> ::Page?
  def page_changed?: () -> bool
  def page_previously_changed?: () -> bool
  def reset_page: () -> void
  def build_page: (?untyped) -> ::Page
  def create_page: (?untyped) -> ::Page
  def create_page!: (?untyped) -> ::Page

  module ::Review::GeneratedAssociationMethods
  end
  include ::Review::GeneratedAssociationMethods

  module ::Review::GeneratedRelationMethods
  end

  class ::Review::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Review]
    include ::Review::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Review, ::String]
  end

  class ::Review::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Review]
    include ::Review::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Review, ::String]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Review
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Review]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Review
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Review]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Review
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Review]
    def reload: () -> ::Array[::Review]

    def replace: (::Array[::Review]) -> void
    def delete: (*::Review | ::String) -> ::Array[::Review]
    def destroy: (*::Review | ::String) -> ::Array[::Review]
    def <<: (*::Review | ::Array[::Review]) -> self
    def prepend: (*::Review | ::Array[::Review]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Page < ::ApplicationRecord
end
