# resolve-type-names: false

class ::ServiceAccount < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::ServiceAccount, ::ServiceAccount::ActiveRecord_Relation, ::String]

  module ::ServiceAccount::GeneratedAttributeMethods
    def id: () -> ::String

    def id=: (::String) -> ::String

    def id?: () -> bool

    def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_change: () -> [ ::String?, ::String? ]

    def id_will_change!: () -> void

    def id_was: () -> ::String?

    def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_previous_change: () -> ::Array[::String?]?

    def id_previously_was: () -> ::String?

    def id_before_last_save: () -> ::String?

    def id_change_to_be_saved: () -> ::Array[::String?]?

    def id_in_database: () -> ::String?

    def saved_change_to_id: () -> ::Array[::String?]?

    def saved_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::String

    def id_for_database: () -> ::String

    def photographer_id: () -> ::String

    def photographer_id=: (::String) -> ::String

    def photographer_id?: () -> bool

    def photographer_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def photographer_id_change: () -> [ ::String?, ::String? ]

    def photographer_id_will_change!: () -> void

    def photographer_id_was: () -> ::String?

    def photographer_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def photographer_id_previous_change: () -> ::Array[::String?]?

    def photographer_id_previously_was: () -> ::String?

    def photographer_id_before_last_save: () -> ::String?

    def photographer_id_change_to_be_saved: () -> ::Array[::String?]?

    def photographer_id_in_database: () -> ::String?

    def saved_change_to_photographer_id: () -> ::Array[::String?]?

    def saved_change_to_photographer_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_photographer_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_photographer_id!: () -> void

    def clear_photographer_id_change: () -> void

    def photographer_id_before_type_cast: () -> ::String

    def photographer_id_for_database: () -> ::String

    def name: () -> ::String

    def name=: (::String) -> ::String

    def name?: () -> bool

    def name_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def name_change: () -> [ ::String?, ::String? ]

    def name_will_change!: () -> void

    def name_was: () -> ::String?

    def name_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def name_previous_change: () -> ::Array[::String?]?

    def name_previously_was: () -> ::String?

    def name_before_last_save: () -> ::String?

    def name_change_to_be_saved: () -> ::Array[::String?]?

    def name_in_database: () -> ::String?

    def saved_change_to_name: () -> ::Array[::String?]?

    def saved_change_to_name?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_name?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_name!: () -> void

    def clear_name_change: () -> void

    def name_before_type_cast: () -> ::String

    def name_for_database: () -> ::String

    def token_digest: () -> ::String

    def token_digest=: (::String) -> ::String

    def token_digest?: () -> bool

    def token_digest_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def token_digest_change: () -> [ ::String?, ::String? ]

    def token_digest_will_change!: () -> void

    def token_digest_was: () -> ::String?

    def token_digest_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def token_digest_previous_change: () -> ::Array[::String?]?

    def token_digest_previously_was: () -> ::String?

    def token_digest_before_last_save: () -> ::String?

    def token_digest_change_to_be_saved: () -> ::Array[::String?]?

    def token_digest_in_database: () -> ::String?

    def saved_change_to_token_digest: () -> ::Array[::String?]?

    def saved_change_to_token_digest?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_token_digest?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_token_digest!: () -> void

    def clear_token_digest_change: () -> void

    def token_digest_before_type_cast: () -> ::String

    def token_digest_for_database: () -> ::String

    def last_used_at: () -> ::ActiveSupport::TimeWithZone?

    def last_used_at=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

    def last_used_at?: () -> bool

    def last_used_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def last_used_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def last_used_at_will_change!: () -> void

    def last_used_at_was: () -> ::ActiveSupport::TimeWithZone?

    def last_used_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def last_used_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def last_used_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def last_used_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def last_used_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def last_used_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_last_used_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_last_used_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_last_used_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_last_used_at!: () -> void

    def clear_last_used_at_change: () -> void

    def last_used_at_before_type_cast: () -> ::Time?

    def last_used_at_for_database: () -> ::Time?

    def revoked_at: () -> ::ActiveSupport::TimeWithZone?

    def revoked_at=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

    def revoked_at?: () -> bool

    def revoked_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def revoked_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def revoked_at_will_change!: () -> void

    def revoked_at_was: () -> ::ActiveSupport::TimeWithZone?

    def revoked_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def revoked_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def revoked_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def revoked_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def revoked_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def revoked_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_revoked_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_revoked_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_revoked_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_revoked_at!: () -> void

    def clear_revoked_at_change: () -> void

    def revoked_at_before_type_cast: () -> ::Time?

    def revoked_at_for_database: () -> ::Time?

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time
  end
  include ::ServiceAccount::GeneratedAttributeMethods
  module ::ServiceAccount::GeneratedAliasAttributeMethods
    include ::ServiceAccount::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::ServiceAccount::GeneratedAliasAttributeMethods

  def photographer: () -> ::Photographer
  def photographer=: (::Photographer?) -> ::Photographer?
  def reload_photographer: () -> ::Photographer?
  def photographer_changed?: () -> bool
  def photographer_previously_changed?: () -> bool
  def reset_photographer: () -> void
  def build_photographer: (?untyped) -> ::Photographer
  def create_photographer: (?untyped) -> ::Photographer
  def create_photographer!: (?untyped) -> ::Photographer

  module ::ServiceAccount::GeneratedAssociationMethods
  end
  include ::ServiceAccount::GeneratedAssociationMethods

  def self.active: () -> ::ServiceAccount::ActiveRecord_Relation

  module ::ServiceAccount::GeneratedRelationMethods
    def active: () -> ::ServiceAccount::ActiveRecord_Relation
  end

  class ::ServiceAccount::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::ServiceAccount]
    include ::ServiceAccount::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::ServiceAccount, ::String]
  end

  class ::ServiceAccount::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::ServiceAccount]
    include ::ServiceAccount::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::ServiceAccount, ::String]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::ServiceAccount
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::ServiceAccount]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::ServiceAccount
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::ServiceAccount]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::ServiceAccount
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::ServiceAccount]
    def reload: () -> ::Array[::ServiceAccount]

    def replace: (::Array[::ServiceAccount]) -> void
    def delete: (*::ServiceAccount | ::String) -> ::Array[::ServiceAccount]
    def destroy: (*::ServiceAccount | ::String) -> ::Array[::ServiceAccount]
    def <<: (*::ServiceAccount | ::Array[::ServiceAccount]) -> self
    def prepend: (*::ServiceAccount | ::Array[::ServiceAccount]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Photographer < ::ApplicationRecord
end
