# resolve-type-names: false

class ::Session < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Session, ::Session::ActiveRecord_Relation, ::String]

  module ::Session::GeneratedAttributeMethods
    def id: () -> ::String

    def id=: (::String) -> ::String

    def id?: () -> bool

    def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_change: () -> [ ::String?, ::String? ]

    def id_will_change!: () -> void

    def id_was: () -> ::String?

    def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_previous_change: () -> ::Array[::String?]?

    def id_previously_was: () -> ::String?

    def id_before_last_save: () -> ::String?

    def id_change_to_be_saved: () -> ::Array[::String?]?

    def id_in_database: () -> ::String?

    def saved_change_to_id: () -> ::Array[::String?]?

    def saved_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::String

    def id_for_database: () -> ::String

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time

    def token_key: () -> ::String?

    def token_key=: (::String?) -> ::String?

    def token_key?: () -> bool

    def token_key_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def token_key_change: () -> [ ::String?, ::String? ]

    def token_key_will_change!: () -> void

    def token_key_was: () -> ::String?

    def token_key_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def token_key_previous_change: () -> ::Array[::String?]?

    def token_key_previously_was: () -> ::String?

    def token_key_before_last_save: () -> ::String?

    def token_key_change_to_be_saved: () -> ::Array[::String?]?

    def token_key_in_database: () -> ::String?

    def saved_change_to_token_key: () -> ::Array[::String?]?

    def saved_change_to_token_key?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_token_key?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_token_key!: () -> void

    def clear_token_key_change: () -> void

    def token_key_before_type_cast: () -> ::String?

    def token_key_for_database: () -> ::String?

    def session_token: () -> ::String?

    def session_token=: (::String?) -> ::String?

    def session_token?: () -> bool

    def session_token_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def session_token_change: () -> [ ::String?, ::String? ]

    def session_token_will_change!: () -> void

    def session_token_was: () -> ::String?

    def session_token_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def session_token_previous_change: () -> ::Array[::String?]?

    def session_token_previously_was: () -> ::String?

    def session_token_before_last_save: () -> ::String?

    def session_token_change_to_be_saved: () -> ::Array[::String?]?

    def session_token_in_database: () -> ::String?

    def saved_change_to_session_token: () -> ::Array[::String?]?

    def saved_change_to_session_token?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_session_token?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_session_token!: () -> void

    def clear_session_token_change: () -> void

    def session_token_before_type_cast: () -> ::String?

    def session_token_for_database: () -> ::String?

    def audience_id: () -> ::String

    def audience_id=: (::String) -> ::String

    def audience_id?: () -> bool

    def audience_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def audience_id_change: () -> [ ::String?, ::String? ]

    def audience_id_will_change!: () -> void

    def audience_id_was: () -> ::String?

    def audience_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def audience_id_previous_change: () -> ::Array[::String?]?

    def audience_id_previously_was: () -> ::String?

    def audience_id_before_last_save: () -> ::String?

    def audience_id_change_to_be_saved: () -> ::Array[::String?]?

    def audience_id_in_database: () -> ::String?

    def saved_change_to_audience_id: () -> ::Array[::String?]?

    def saved_change_to_audience_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_audience_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_audience_id!: () -> void

    def clear_audience_id_change: () -> void

    def audience_id_before_type_cast: () -> ::String

    def audience_id_for_database: () -> ::String

    def device_id: () -> ::String?

    def device_id=: (::String?) -> ::String?

    def device_id?: () -> bool

    def device_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def device_id_change: () -> [ ::String?, ::String? ]

    def device_id_will_change!: () -> void

    def device_id_was: () -> ::String?

    def device_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def device_id_previous_change: () -> ::Array[::String?]?

    def device_id_previously_was: () -> ::String?

    def device_id_before_last_save: () -> ::String?

    def device_id_change_to_be_saved: () -> ::Array[::String?]?

    def device_id_in_database: () -> ::String?

    def saved_change_to_device_id: () -> ::Array[::String?]?

    def saved_change_to_device_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_device_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_device_id!: () -> void

    def clear_device_id_change: () -> void

    def device_id_before_type_cast: () -> ::String?

    def device_id_for_database: () -> ::String?

    def user_id: () -> ::String?

    def user_id=: (::String?) -> ::String?

    def user_id?: () -> bool

    def user_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def user_id_change: () -> [ ::String?, ::String? ]

    def user_id_will_change!: () -> void

    def user_id_was: () -> ::String?

    def user_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def user_id_previous_change: () -> ::Array[::String?]?

    def user_id_previously_was: () -> ::String?

    def user_id_before_last_save: () -> ::String?

    def user_id_change_to_be_saved: () -> ::Array[::String?]?

    def user_id_in_database: () -> ::String?

    def saved_change_to_user_id: () -> ::Array[::String?]?

    def saved_change_to_user_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_user_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_user_id!: () -> void

    def clear_user_id_change: () -> void

    def user_id_before_type_cast: () -> ::String?

    def user_id_for_database: () -> ::String?

    def origin_ip: () -> ::IPAddr?

    def origin_ip=: (::IPAddr?) -> ::IPAddr?

    def origin_ip?: () -> bool

    def origin_ip_changed?: (?from: ::IPAddr?, ?to: ::IPAddr?) -> bool

    def origin_ip_change: () -> [ ::IPAddr?, ::IPAddr? ]

    def origin_ip_will_change!: () -> void

    def origin_ip_was: () -> ::IPAddr?

    def origin_ip_previously_changed?: (?from: ::IPAddr?, ?to: ::IPAddr?) -> bool

    def origin_ip_previous_change: () -> ::Array[::IPAddr?]?

    def origin_ip_previously_was: () -> ::IPAddr?

    def origin_ip_before_last_save: () -> ::IPAddr?

    def origin_ip_change_to_be_saved: () -> ::Array[::IPAddr?]?

    def origin_ip_in_database: () -> ::IPAddr?

    def saved_change_to_origin_ip: () -> ::Array[::IPAddr?]?

    def saved_change_to_origin_ip?: (?from: ::IPAddr?, ?to: ::IPAddr?) -> bool

    def will_save_change_to_origin_ip?: (?from: ::IPAddr?, ?to: ::IPAddr?) -> bool

    def restore_origin_ip!: () -> void

    def clear_origin_ip_change: () -> void

    def origin_ip_before_type_cast: () -> ::IPAddr?

    def origin_ip_for_database: () -> ::IPAddr?

    def location: () -> untyped

    def location=: (untyped) -> untyped

    def location?: () -> bool

    def location_changed?: (?from: untyped, ?to: untyped) -> bool

    def location_change: () -> [ untyped, untyped ]

    def location_will_change!: () -> void

    def location_was: () -> untyped

    def location_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    def location_previous_change: () -> ::Array[untyped]?

    def location_previously_was: () -> untyped

    def location_before_last_save: () -> untyped

    def location_change_to_be_saved: () -> ::Array[untyped]?

    def location_in_database: () -> untyped

    def saved_change_to_location: () -> ::Array[untyped]?

    def saved_change_to_location?: (?from: untyped, ?to: untyped) -> bool

    def will_save_change_to_location?: (?from: untyped, ?to: untyped) -> bool

    def restore_location!: () -> void

    def clear_location_change: () -> void

    def location_before_type_cast: () -> untyped?

    def location_for_database: () -> untyped?

    def version: () -> ::String?

    def version=: (::String?) -> ::String?

    def version?: () -> bool

    def version_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def version_change: () -> [ ::String?, ::String? ]

    def version_will_change!: () -> void

    def version_was: () -> ::String?

    def version_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def version_previous_change: () -> ::Array[::String?]?

    def version_previously_was: () -> ::String?

    def version_before_last_save: () -> ::String?

    def version_change_to_be_saved: () -> ::Array[::String?]?

    def version_in_database: () -> ::String?

    def saved_change_to_version: () -> ::Array[::String?]?

    def saved_change_to_version?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_version?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_version!: () -> void

    def clear_version_change: () -> void

    def version_before_type_cast: () -> ::String?

    def version_for_database: () -> ::String?

    def build: () -> ::Integer?

    def build=: (::Integer?) -> ::Integer?

    def build?: () -> bool

    def build_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def build_change: () -> [ ::Integer?, ::Integer? ]

    def build_will_change!: () -> void

    def build_was: () -> ::Integer?

    def build_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def build_previous_change: () -> ::Array[::Integer?]?

    def build_previously_was: () -> ::Integer?

    def build_before_last_save: () -> ::Integer?

    def build_change_to_be_saved: () -> ::Array[::Integer?]?

    def build_in_database: () -> ::Integer?

    def saved_change_to_build: () -> ::Array[::Integer?]?

    def saved_change_to_build?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_build?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_build!: () -> void

    def clear_build_change: () -> void

    def build_before_type_cast: () -> ::Integer?

    def build_for_database: () -> ::Integer?
  end
  include ::Session::GeneratedAttributeMethods
  module ::Session::GeneratedAliasAttributeMethods
    include ::Session::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::Session::GeneratedAliasAttributeMethods

  def device: () -> ::Device
  def device=: (::Device?) -> ::Device?
  def reload_device: () -> ::Device?
  def build_device: (?untyped) -> ::Device
  def create_device: (?untyped) -> ::Device
  def create_device!: (?untyped) -> ::Device
  def user: () -> ::User
  def user=: (::User?) -> ::User?
  def reload_user: () -> ::User?
  def build_user: (?untyped) -> ::User
  def create_user: (?untyped) -> ::User
  def create_user!: (?untyped) -> ::User

  module ::Session::GeneratedAssociationMethods
  end
  include ::Session::GeneratedAssociationMethods

  module ::Session::GeneratedRelationMethods
  end

  class ::Session::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Session]
    include ::Session::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Session, ::String]
  end

  class ::Session::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Session]
    include ::Session::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Session, ::String]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Session
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Session]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Session
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Session]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Session
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Session]
    def reload: () -> ::Array[::Session]

    def replace: (::Array[::Session]) -> void
    def delete: (*::Session | ::String) -> ::Array[::Session]
    def destroy: (*::Session | ::String) -> ::Array[::Session]
    def <<: (*::Session | ::Array[::Session]) -> self
    def prepend: (*::Session | ::Array[::Session]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Device < ::ApplicationRecord
end
class ::User < ::ApplicationRecord
end
