# resolve-type-names: false

class ::Tenant < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Tenant, ::Tenant::ActiveRecord_Relation, ::String]

  module ::Tenant::GeneratedAttributeMethods
    def id: () -> ::String

    def id=: (::String) -> ::String

    def id?: () -> bool

    def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_change: () -> [::String?, ::String?]

    def id_will_change!: () -> void

    def id_was: () -> ::String?

    def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_previous_change: () -> ::Array[::String?]?

    def id_previously_was: () -> ::String?

    def id_before_last_save: () -> ::String?

    def id_change_to_be_saved: () -> ::Array[::String?]?

    def id_in_database: () -> ::String?

    def saved_change_to_id: () -> ::Array[::String?]?

    def saved_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::String

    def id_for_database: () -> ::String

    def active: () -> bool

    def active=: (bool) -> bool

    def active?: () -> bool

    def active_changed?: (?from: bool?, ?to: bool?) -> bool

    def active_change: () -> [bool?, bool?]

    def active_will_change!: () -> void

    def active_was: () -> bool?

    def active_previously_changed?: (?from: bool?, ?to: bool?) -> bool

    def active_previous_change: () -> ::Array[bool?]?

    def active_previously_was: () -> bool?

    def active_before_last_save: () -> bool?

    def active_change_to_be_saved: () -> ::Array[bool?]?

    def active_in_database: () -> bool?

    def saved_change_to_active: () -> ::Array[bool?]?

    def saved_change_to_active?: (?from: bool?, ?to: bool?) -> bool

    def will_save_change_to_active?: (?from: bool?, ?to: bool?) -> bool

    def restore_active!: () -> void

    def clear_active_change: () -> void

    def active_before_type_cast: () -> bool

    def active_for_database: () -> bool

    def api_key: () -> ::String

    def api_key=: (::String) -> ::String

    def api_key?: () -> bool

    def api_key_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def api_key_change: () -> [::String?, ::String?]

    def api_key_will_change!: () -> void

    def api_key_was: () -> ::String?

    def api_key_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def api_key_previous_change: () -> ::Array[::String?]?

    def api_key_previously_was: () -> ::String?

    def api_key_before_last_save: () -> ::String?

    def api_key_change_to_be_saved: () -> ::Array[::String?]?

    def api_key_in_database: () -> ::String?

    def saved_change_to_api_key: () -> ::Array[::String?]?

    def saved_change_to_api_key?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_api_key?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_api_key!: () -> void

    def clear_api_key_change: () -> void

    def api_key_before_type_cast: () -> ::String

    def api_key_for_database: () -> ::String

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone?]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def name: () -> ::String

    def name=: (::String) -> ::String

    def name?: () -> bool

    def name_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def name_change: () -> [::String?, ::String?]

    def name_will_change!: () -> void

    def name_was: () -> ::String?

    def name_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def name_previous_change: () -> ::Array[::String?]?

    def name_previously_was: () -> ::String?

    def name_before_last_save: () -> ::String?

    def name_change_to_be_saved: () -> ::Array[::String?]?

    def name_in_database: () -> ::String?

    def saved_change_to_name: () -> ::Array[::String?]?

    def saved_change_to_name?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_name?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_name!: () -> void

    def clear_name_change: () -> void

    def name_before_type_cast: () -> ::String

    def name_for_database: () -> ::String

    def subdomain: () -> ::String

    def subdomain=: (::String) -> ::String

    def subdomain?: () -> bool

    def subdomain_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def subdomain_change: () -> [::String?, ::String?]

    def subdomain_will_change!: () -> void

    def subdomain_was: () -> ::String?

    def subdomain_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def subdomain_previous_change: () -> ::Array[::String?]?

    def subdomain_previously_was: () -> ::String?

    def subdomain_before_last_save: () -> ::String?

    def subdomain_change_to_be_saved: () -> ::Array[::String?]?

    def subdomain_in_database: () -> ::String?

    def saved_change_to_subdomain: () -> ::Array[::String?]?

    def saved_change_to_subdomain?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_subdomain?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_subdomain!: () -> void

    def clear_subdomain_change: () -> void

    def subdomain_before_type_cast: () -> ::String

    def subdomain_for_database: () -> ::String

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone?]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time
  end

  include ::Tenant::GeneratedAttributeMethods

  module ::Tenant::GeneratedAliasAttributeMethods
    include ::Tenant::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end

  include ::Tenant::GeneratedAliasAttributeMethods

  def photos: () -> ::Photo::ActiveRecord_Associations_CollectionProxy

  def photos=: (::Photo::ActiveRecord_Associations_CollectionProxy | ::Array[::Photo]) -> (::Photo::ActiveRecord_Associations_CollectionProxy | ::Array[::Photo])

  def photo_ids: () -> ::Array[::String]

  def photo_ids=: (::Array[::String]) -> ::Array[::String]

  def venues: () -> ::Venue::ActiveRecord_Associations_CollectionProxy

  def venues=: (::Venue::ActiveRecord_Associations_CollectionProxy | ::Array[::Venue]) -> (::Venue::ActiveRecord_Associations_CollectionProxy | ::Array[::Venue])

  def venue_ids: () -> ::Array[::String]

  def venue_ids=: (::Array[::String]) -> ::Array[::String]

  def people: () -> ::Person::ActiveRecord_Associations_CollectionProxy

  def people=: (::Person::ActiveRecord_Associations_CollectionProxy | ::Array[::Person]) -> (::Person::ActiveRecord_Associations_CollectionProxy | ::Array[::Person])

  def person_ids: () -> ::Array[::String]

  def person_ids=: (::Array[::String]) -> ::Array[::String]

  module ::Tenant::GeneratedAssociationMethods
  end

  include ::Tenant::GeneratedAssociationMethods

  def self.active: () -> ::Tenant::ActiveRecord_Relation

  module ::Tenant::GeneratedRelationMethods
    def active: () -> ::Tenant::ActiveRecord_Relation
  end

  class ::Tenant::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Tenant]
    include ::Tenant::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Tenant, ::String]
  end

  class ::Tenant::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Tenant]
    include ::Tenant::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Tenant, ::String]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Tenant
      | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Tenant]

    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Tenant
      | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Tenant]

    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Tenant
      | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Tenant]

    def reload: () -> ::Array[::Tenant]

    def replace: (::Array[::Tenant]) -> void

    def delete: (*::Tenant | ::String) -> ::Array[::Tenant]

    def destroy: (*::Tenant | ::String) -> ::Array[::Tenant]

    def <<: (*::Tenant | ::Array[::Tenant]) -> self

    def prepend: (*::Tenant | ::Array[::Tenant]) -> self
  end

  def self.default_tenant: () -> Tenant
end

class ::ApplicationRecord < ::ActiveRecord::Base
end

class ::Photo < ::ApplicationRecord
end

class ::Photo::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end

class ::Venue < ::ApplicationRecord
end

class ::Venue::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end

class ::Person < ::ApplicationRecord
end

class ::Person::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
