# resolve-type-names: false

class ::Venue < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Venue, ::Venue::ActiveRecord_Relation, ::String]

  module ::Venue::GeneratedAttributeMethods
    def id: () -> ::String

    def id=: (::String) -> ::String

    def id?: () -> bool

    def id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_change: () -> [ ::String?, ::String? ]

    def id_will_change!: () -> void

    def id_was: () -> ::String?

    def id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def id_previous_change: () -> ::Array[::String?]?

    def id_previously_was: () -> ::String?

    def id_before_last_save: () -> ::String?

    def id_change_to_be_saved: () -> ::Array[::String?]?

    def id_in_database: () -> ::String?

    def saved_change_to_id: () -> ::Array[::String?]?

    def saved_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::String

    def id_for_database: () -> ::String

    def audience_id: () -> ::String

    def audience_id=: (::String) -> ::String

    def audience_id?: () -> bool

    def audience_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def audience_id_change: () -> [ ::String?, ::String? ]

    def audience_id_will_change!: () -> void

    def audience_id_was: () -> ::String?

    def audience_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def audience_id_previous_change: () -> ::Array[::String?]?

    def audience_id_previously_was: () -> ::String?

    def audience_id_before_last_save: () -> ::String?

    def audience_id_change_to_be_saved: () -> ::Array[::String?]?

    def audience_id_in_database: () -> ::String?

    def saved_change_to_audience_id: () -> ::Array[::String?]?

    def saved_change_to_audience_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_audience_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_audience_id!: () -> void

    def clear_audience_id_change: () -> void

    def audience_id_before_type_cast: () -> ::String

    def audience_id_for_database: () -> ::String

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def distance_tolerance: () -> ::Integer

    def distance_tolerance=: (::Integer) -> ::Integer

    def distance_tolerance?: () -> bool

    def distance_tolerance_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def distance_tolerance_change: () -> [ ::Integer?, ::Integer? ]

    def distance_tolerance_will_change!: () -> void

    def distance_tolerance_was: () -> ::Integer?

    def distance_tolerance_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def distance_tolerance_previous_change: () -> ::Array[::Integer?]?

    def distance_tolerance_previously_was: () -> ::Integer?

    def distance_tolerance_before_last_save: () -> ::Integer?

    def distance_tolerance_change_to_be_saved: () -> ::Array[::Integer?]?

    def distance_tolerance_in_database: () -> ::Integer?

    def saved_change_to_distance_tolerance: () -> ::Array[::Integer?]?

    def saved_change_to_distance_tolerance?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_distance_tolerance?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_distance_tolerance!: () -> void

    def clear_distance_tolerance_change: () -> void

    def distance_tolerance_before_type_cast: () -> ::Integer

    def distance_tolerance_for_database: () -> ::Integer

    def hidden: () -> bool

    def hidden=: (bool) -> bool

    def hidden?: () -> bool

    def hidden_changed?: (?from: bool?, ?to: bool?) -> bool

    def hidden_change: () -> [ bool?, bool? ]

    def hidden_will_change!: () -> void

    def hidden_was: () -> bool?

    def hidden_previously_changed?: (?from: bool?, ?to: bool?) -> bool

    def hidden_previous_change: () -> ::Array[bool?]?

    def hidden_previously_was: () -> bool?

    def hidden_before_last_save: () -> bool?

    def hidden_change_to_be_saved: () -> ::Array[bool?]?

    def hidden_in_database: () -> bool?

    def saved_change_to_hidden: () -> ::Array[bool?]?

    def saved_change_to_hidden?: (?from: bool?, ?to: bool?) -> bool

    def will_save_change_to_hidden?: (?from: bool?, ?to: bool?) -> bool

    def restore_hidden!: () -> void

    def clear_hidden_change: () -> void

    def hidden_before_type_cast: () -> bool

    def hidden_for_database: () -> bool

    def locale_id: () -> ::String

    def locale_id=: (::String) -> ::String

    def locale_id?: () -> bool

    def locale_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def locale_id_change: () -> [ ::String?, ::String? ]

    def locale_id_will_change!: () -> void

    def locale_id_was: () -> ::String?

    def locale_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def locale_id_previous_change: () -> ::Array[::String?]?

    def locale_id_previously_was: () -> ::String?

    def locale_id_before_last_save: () -> ::String?

    def locale_id_change_to_be_saved: () -> ::Array[::String?]?

    def locale_id_in_database: () -> ::String?

    def saved_change_to_locale_id: () -> ::Array[::String?]?

    def saved_change_to_locale_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_locale_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_locale_id!: () -> void

    def clear_locale_id_change: () -> void

    def locale_id_before_type_cast: () -> ::String

    def locale_id_for_database: () -> ::String

    def location_id: () -> ::String

    def location_id=: (::String) -> ::String

    def location_id?: () -> bool

    def location_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def location_id_change: () -> [ ::String?, ::String? ]

    def location_id_will_change!: () -> void

    def location_id_was: () -> ::String?

    def location_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def location_id_previous_change: () -> ::Array[::String?]?

    def location_id_previously_was: () -> ::String?

    def location_id_before_last_save: () -> ::String?

    def location_id_change_to_be_saved: () -> ::Array[::String?]?

    def location_id_in_database: () -> ::String?

    def saved_change_to_location_id: () -> ::Array[::String?]?

    def saved_change_to_location_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_location_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_location_id!: () -> void

    def clear_location_id_change: () -> void

    def location_id_before_type_cast: () -> ::String

    def location_id_for_database: () -> ::String

    def order: () -> ::Integer

    def order=: (::Integer) -> ::Integer

    def order?: () -> bool

    def order_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def order_change: () -> [ ::Integer?, ::Integer? ]

    def order_will_change!: () -> void

    def order_was: () -> ::Integer?

    def order_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def order_previous_change: () -> ::Array[::Integer?]?

    def order_previously_was: () -> ::Integer?

    def order_before_last_save: () -> ::Integer?

    def order_change_to_be_saved: () -> ::Array[::Integer?]?

    def order_in_database: () -> ::Integer?

    def saved_change_to_order: () -> ::Array[::Integer?]?

    def saved_change_to_order?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_order?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_order!: () -> void

    def clear_order_change: () -> void

    def order_before_type_cast: () -> ::Integer

    def order_for_database: () -> ::Integer

    def page_id: () -> ::String

    def page_id=: (::String) -> ::String

    def page_id?: () -> bool

    def page_id_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def page_id_change: () -> [ ::String?, ::String? ]

    def page_id_will_change!: () -> void

    def page_id_was: () -> ::String?

    def page_id_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def page_id_previous_change: () -> ::Array[::String?]?

    def page_id_previously_was: () -> ::String?

    def page_id_before_last_save: () -> ::String?

    def page_id_change_to_be_saved: () -> ::Array[::String?]?

    def page_id_in_database: () -> ::String?

    def saved_change_to_page_id: () -> ::Array[::String?]?

    def saved_change_to_page_id?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_page_id?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_page_id!: () -> void

    def clear_page_id_change: () -> void

    def page_id_before_type_cast: () -> ::String

    def page_id_for_database: () -> ::String

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time
  end
  include ::Venue::GeneratedAttributeMethods
  module ::Venue::GeneratedAliasAttributeMethods
    include ::Venue::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::Venue::GeneratedAliasAttributeMethods
  def events: () -> ::Event::ActiveRecord_Associations_CollectionProxy
  def events=: (::Event::ActiveRecord_Associations_CollectionProxy | ::Array[::Event]) -> (::Event::ActiveRecord_Associations_CollectionProxy | ::Array[::Event])
  def event_ids: () -> ::Array[::String]
  def event_ids=: (::Array[::String]) -> ::Array[::String]
  def users: () -> ::User::ActiveRecord_Associations_CollectionProxy
  def users=: (::User::ActiveRecord_Associations_CollectionProxy | ::Array[::User]) -> (::User::ActiveRecord_Associations_CollectionProxy | ::Array[::User])
  def user_ids: () -> ::Array[::String]
  def user_ids=: (::Array[::String]) -> ::Array[::String]

  def page: () -> ::Page?
  def page=: (::Page?) -> ::Page?
  def build_page: (?untyped) -> ::Page
  def create_page: (?untyped) -> ::Page
  def create_page!: (?untyped) -> ::Page
  def reload_page: () -> ::Page?
  def location: () -> ::Location
  def location=: (::Location?) -> ::Location?
  def reload_location: () -> ::Location?
  def build_location: (?untyped) -> ::Location
  def create_location: (?untyped) -> ::Location
  def create_location!: (?untyped) -> ::Location
  def image: () -> ::Image
  def image=: (::Image?) -> ::Image?
  def reload_image: () -> ::Image?
  def build_image: (?untyped) -> ::Image
  def create_image: (?untyped) -> ::Image
  def create_image!: (?untyped) -> ::Image
  def locale: () -> ::Locale
  def locale=: (::Locale?) -> ::Locale?
  def reload_locale: () -> ::Locale?
  def build_locale: (?untyped) -> ::Locale
  def create_locale: (?untyped) -> ::Locale
  def create_locale!: (?untyped) -> ::Locale

  module ::Venue::GeneratedAssociationMethods
  end
  include ::Venue::GeneratedAssociationMethods

  module ::Venue::GeneratedRelationMethods
  end

  class ::Venue::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Venue]
    include ::Venue::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Venue, ::String]
  end

  class ::Venue::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Venue]
    include ::Venue::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Venue, ::String]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Venue
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Venue]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Venue
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Venue]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Venue
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Venue]
    def reload: () -> ::Array[::Venue]

    def replace: (::Array[::Venue]) -> void
    def delete: (*::Venue | ::String) -> ::Array[::Venue]
    def destroy: (*::Venue | ::String) -> ::Array[::Venue]
    def <<: (*::Venue | ::Array[::Venue]) -> self
    def prepend: (*::Venue | ::Array[::Venue]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Event < ::ApplicationRecord
end
class ::Event::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::User < ::ApplicationRecord
end
class ::User::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Page < ::ApplicationRecord
end
class ::Location < ::ApplicationRecord
end
class ::Image < ::ApplicationRecord
end
class ::Locale < ::ApplicationRecord
end
