class Folder < ApplicationRecord
  @id: string

  attr_accessor name: String
  attr_accessor photos: Array[Photo]

  def to_gid_param: () -> String

  def initialize: (String, Array[Photo]) -> void

  def self.find: (string) -> Folder
end
