# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rbs_inline
  - rubocop-rake
  - rubocop-rspec


AllCops:
  NewCops: enable

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
