module Types
  module BaseInterface
    include GraphQL::Schema::Interface

    def self.edge_type_class: (Class) -> void

    def self.connection_type_class: (Class) -> void

    def self.field_class: (Class) -> void
  end
end