module ClusterKit
  module Clustering
    class HDBSCAN
      type metric = "euclidean"
      def initialize: (min_samples: Integer, min_cluster_size: Integer, metric: metric) -> void
      def fit_predict: (Array[Array[_ToF]]) -> untyped
    end
  end
end