class ApplicationController < ActionController::Base
  @current_user: User?

  private

  def current_user: () -> User?
  def photographer: () -> Photographer
  def set_photographer: () -> untyped
  def resolve_photographer: () -> Photographer?
end
