class GraphqlController < ApplicationController
  def execute: () -> untyped

  private

  def resolve_photographer: () -> Photographer?
  def prepare_variables: (untyped) -> untyped
  def handle_error_in_development: (StandardError) -> untyped
end
