module ActiveStorage
  # Decorated proxy object representing of multiple attachments to a model.
  class Attached::Many < Attached
    include Enumerable[Attachment]
    def purge: -> void
  end

  class Attachment
    def url: -> _ToStr
    def open: () { (File) -> void } -> void
    attr_reader content_type: _ToStr
  end
end