module Types
  class BaseObject < GraphQL::Schema::Object
    def self.field: (?Symbol, ?untyped, ?String, **untyped) ?{ (GraphQL::Schema::Field) [self: GraphQL::Schema::Field] -> void } -> GraphQL::Schema::Field
  end
end
